- name: Restart docker containers that are supposed to be up
  hosts: perm1
  become: true
  tasks:
    - name: Copy restart script
      copy:
        src: ../templates/restart-docker.sh
        dest: /usr/bin/restart-docker.sh
        mode: '0755'
    
    - name: Copy systemd service
      synchronize:
        src: ../templates/restart-docker.service
        dest: /etc/systemd/system/restart-docker.service

    - name: Copy systemd timer
      synchronize:
        src: ../templates/restart-docker.timer
        dest: /etc/systemd/system/restart-docker.timer

    - name: Set up service
      ansible.builtin.systemd_service:
        name: restart-docker.service
        state: stopped
        daemon_reload: true
        enabled: true

    - name: Set up timer
      ansible.builtin.systemd_service:
        name: restart-docker.timer
        state: started
        daemon_reload: true
        enabled: true

