- name: Set up cpu power profile service
  hosts: all
  become: true
  tasks:
    - name: Packages
      apt:
        pkg:
          - linux-cpupower
          - cpufrequtils
        state: latest
        update_cache: true
    
    - name: Copy systemd service
      synchronize:
        src: ./templates/cpupower.service
        dest: /etc/systemd/system/cpupower.service

    - name: Set up service
      ansible.builtin.systemd_service:
        name: cpupower.service
        state: started
        daemon_reload: true
        enabled: true

